#!/usr/bin/env python3
"""
report_gen.py
=============
Reads results.json and generates a PDF evaluation report using fpdf2.

Usage:
    python report_gen.py \\
        --results_json /app/output/results.json \\
        --output_dir   /app/output
"""

import argparse
import json
import os
import sys
from datetime import datetime
from typing import List, Optional

from fpdf import FPDF


# ──────────────────────────────────────────────────────────────────────────────
# Colour palette
# ──────────────────────────────────────────────────────────────────────────────
OSIPI_BLUE   = (0,  70, 140)    # dark blue
OSIPI_LIGHT  = (220, 235, 252)  # light-blue cell fill
WHITE        = (255, 255, 255)
PASS_GREEN   = (0,  140,   0)
FAIL_RED     = (200,   0,   0)
GREY_BG      = (245, 245, 245)
DARK_TEXT    = (30,  30,  30)


# ──────────────────────────────────────────────────────────────────────────────
# PDF class
# ──────────────────────────────────────────────────────────────────────────────

class EvalReport(FPDF):

    def header(self):
        # Blue banner
        self.set_fill_color(*OSIPI_BLUE)
        self.rect(0, 0, 210, 22, 'F')
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(*WHITE)
        self.set_y(6)
        self.cell(0, 10, "OSIPI DCE-MRI Challenge Evaluation", align="C")
        self.set_text_color(*DARK_TEXT)
        self.ln(20)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by OSIPI Automated Evaluation Pipeline", align="C")

    # ── Section heading ───────────────────────────────────────────────────────────
    def section_title(self, title: str):
        self.ln(4)
        self.set_fill_color(*OSIPI_BLUE)
        self.set_text_color(*WHITE)
        self.set_font("Helvetica", "B", 11)
        self.cell(0, 8, f"  {title}", fill=True, ln=True)
        self.set_text_color(*DARK_TEXT)
        self.ln(3)

    # ── Key-value row ─────────────────────────────────────────────────────────────
    def kv_row(self, key: str, value: str, shade: bool = False):
        self.set_font("Helvetica", "", 10)
        if shade:
            self.set_fill_color(*GREY_BG)
            fill = True
        else:
            fill = False
        self.cell(85, 7, f"  {key}", border=0, fill=fill)
        self.cell(0,  7, str(value), border=0, fill=fill, ln=True)

    # ── Validation badge ──────────────────────────────────────────────────────────
    def validation_badge(self, passed: bool, errors: Optional[List[str]] = None):
        self.set_font("Helvetica", "B", 12)
        if passed:
            self.set_fill_color(*PASS_GREEN)
            self.set_text_color(*WHITE)
            self.cell(0, 10, "  [PASS]  VALIDATION PASSED", fill=True, ln=True)
        else:
            self.set_fill_color(*FAIL_RED)
            self.set_text_color(*WHITE)
            self.cell(0, 10, "  [FAIL]  VALIDATION FAILED", fill=True, ln=True)
            if errors:
                self.set_text_color(*FAIL_RED)
                self.set_font("Helvetica", "", 9)
                for err in errors:
                    self.cell(0, 6, f"    - {err}", ln=True)
        self.set_text_color(*DARK_TEXT)
        self.ln(4)

    # ── Score summary table ───────────────────────────────────────────────────────
    def score_table(self, scores: dict):
        col_w = [100, 50, 40]
        headers = ["Metric", "Score", "Max"]

        # Header row
        self.set_fill_color(*OSIPI_BLUE)
        self.set_text_color(*WHITE)
        self.set_font("Helvetica", "B", 10)
        for header, w in zip(headers, col_w):
            self.cell(w, 8, f"  {header}", fill=True)
        self.ln()
        self.set_text_color(*DARK_TEXT)

        rows = [
            ("Accuracy Score",          scores.get("accuracy_score"),        "1.000"),
            ("Repeatability Score",     scores.get("repeatability_score"),   "1.000"),
            ("Reproducibility Score",   scores.get("reproducibility_score"), "1.000"),
            ("OSIPI Score (Silver) %",  scores.get("osipi_score_silver"),    "100.0"),
            ("OSIPI Score (Gold) %",    scores.get("osipi_score_gold"),      "100.0"),
        ]
        for idx, (label, val, max_val) in enumerate(rows):
            fill = (idx % 2 == 0)
            bg = OSIPI_LIGHT if fill else WHITE
            self.set_fill_color(*bg)
            self.set_font("Helvetica", "", 10)
            val_str = f"{val:.4f}" if isinstance(val, float) else str(val or "N/A")
            self.cell(col_w[0], 7, f"  {label}", fill=True)
            self.cell(col_w[1], 7, val_str,       fill=True, align="C")
            self.cell(col_w[2], 7, max_val,        fill=True, align="C")
            self.ln()
        self.ln(3)

    # ── Per-patient Ktrans table ──────────────────────────────────────────────────
    def ktrans_table(self, ktrans: dict):
        if not ktrans:
            self.set_font("Helvetica", "I", 9)
            self.cell(0, 7, "  No per-patient data available.", ln=True)
            return

        col_w = [60, 50, 50, 30]
        headers = ["Patient", "Type", "Visit", "Mean Ktrans"]

        # Header row
        self.set_fill_color(*OSIPI_BLUE)
        self.set_text_color(*WHITE)
        self.set_font("Helvetica", "B", 10)
        for header, w in zip(headers, col_w):
            self.cell(w, 8, f"  {header}", fill=True)
        self.ln()
        self.set_text_color(*DARK_TEXT)

        # Parse label like "C1_v1" → Type=Clinical, Patient=1, Visit=1
        # or "S1_v2" → Type=Synthetic, Patient=1, Visit=2
        parsed = []
        for label, val in ktrans.items():
            m_type    = "Clinical"  if label.upper().startswith("C") else "Synthetic"
            rest      = label[1:]   # e.g. "1_v1"
            parts     = rest.split("_")
            p_num     = parts[0] if parts else "?"
            v_num     = parts[1].replace("v","") if len(parts) > 1 else "?"
            val_str   = f"{val:.4f}" if isinstance(val, float) else str(val)
            parsed.append((m_type, p_num, v_num, val_str, label))

        # Sort: Synthetic first, then Clinical; then by patient num, then visit
        parsed.sort(key=lambda x: (0 if x[0] == "Synthetic" else 1, int(x[1]) if x[1].isdigit() else 99, x[2]))

        for idx, (m_type, p_num, v_num, val_str, _) in enumerate(parsed):
            fill = (idx % 2 == 0)
            bg   = OSIPI_LIGHT if fill else WHITE
            self.set_fill_color(*bg)
            self.set_font("Helvetica", "", 10)
            self.cell(col_w[0], 7, f"  P{p_num}",   fill=True)
            self.cell(col_w[1], 7, m_type,            fill=True)
            self.cell(col_w[2], 7, f"Visit {v_num}",  fill=True)
            self.cell(col_w[3], 7, val_str,            fill=True, align="C")
            self.ln()
        self.ln(3)


# ──────────────────────────────────────────────────────────────────────────────
# Main
# ──────────────────────────────────────────────────────────────────────────────

def generate_report(results_json_path: str, output_dir: str) -> str:
    """
    Generate Evaluation_Report.pdf from results.json.
    Returns the path of the generated PDF.
    """
    os.makedirs(output_dir, exist_ok=True)

    with open(results_json_path, 'r') as f:
        results = json.load(f)

    pdf = EvalReport()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # ── Meta info ────────────────────────────────────────────────────────────────
    pdf.section_title("Pipeline Run Information")
    pdf.kv_row("Generated at",  datetime.now().strftime("%Y-%m-%d %H:%M:%S"), shade=False)
    pdf.kv_row("Team / Entry",  results.get("team", "N/A"),                   shade=True)
    pdf.ln(2)

    # ── Validation status ─────────────────────────────────────────────────────────
    pdf.section_title("File Validation Status")
    validation_passed = results.get("validation_passed", False)
    validation_errors = results.get("validation_errors", [])
    pdf.validation_badge(passed=validation_passed, errors=validation_errors)

    # ── Score summary ─────────────────────────────────────────────────────────────
    pdf.section_title("Score Summary")
    pdf.score_table(results)

    # ── Per-patient Ktrans ────────────────────────────────────────────────────────
    pdf.section_title("Per-Patient Mean Tumour Ktrans")
    pdf.ktrans_table(results.get("per_patient_ktrans", {}))

    # ── Notes ─────────────────────────────────────────────────────────────────────
    pdf.section_title("Notes")
    pdf.set_font("Helvetica", "", 9)
    notes = [
        "Scores are calculated using the OSIPI Challenge scoring methodology.",
        "Accuracy Score: exp(-mean CV) comparing submission vs. DRO ground truth.",
        "Repeatability Score: exp(-mean CV) across clinical patient test-retest visits.",
        "Reproducibility Score: exp(-mean CV) between original and neutral-team reproductions.",
        "OSIPI Silver = Accuracy x Repeatability x 100%",
        "OSIPI Gold   = Accuracy x Repeatability x Reproducibility x 100%",
        f"Raw scoring outputs are saved alongside this report in: {output_dir}",
    ]
    for note in notes:
        pdf.cell(0, 5, f"  - {note}", ln=True)

    out_path = os.path.join(output_dir, "Evaluation_Report.pdf")
    pdf.output(out_path)
    print(f"[Reporter] PDF report written to: {out_path}")
    return out_path


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="OSIPI DCE-MRI Evaluation Report Generator")
    parser.add_argument("--results_json", required=True, help="Path to results.json")
    parser.add_argument("--output_dir",   required=True, help="Directory to save the PDF")
    args = parser.parse_args()

    try:
        generate_report(args.results_json, args.output_dir)
    except Exception as e:
        print(f"[Reporter] ERROR: {e}", file=sys.stderr)
        sys.exit(1)
